<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtX7N05\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtX7N05/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLtX7N05.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLtX7N05\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLtX7N05\App_KernelDevDebugContainer([
    'container.build_hash' => 'LtX7N05',
    'container.build_id' => 'fbfb7274',
    'container.build_time' => 1647069537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtX7N05');
